export const data = {
  truth: [
    'What is your biggest fear?',
    'What has been your most embarrassing moment?',
    'What is your biggest regret?',
    'What is your biggest secret?',
    'What is your greatest achievement?',
    'What is your favorite movie?',
    'What is your favorite song?',
    'What is your favorite food?',
    'What is your favorite hobby?',
    'Who is your biggest inspiration?',
    'What is your biggest pet peeve?',
    'What is your favorite place in the world?',
    'What is your greatest talent?',
    'What is your worst habit?',
    'What is your biggest dream?',
  ],
  dare: [
    'Dance to a song in front of all the players.',
    'Make a prank call to someone you know.',
    'Do 10 push-ups.',
    'Eat something spicy without drinking water for one minute.',
    'Imitate your favorite celebrity.',
    'Do an animal impersonation and let others guess which animal it is.',
    'Sing a song in a foreign language.',
    'Flip someone off without laughing.',
    'Perform a choreography to a popular song.',
    "Eat something you've never tried before.",
    'Make a phone call with the most exaggerated accent you can.',
    'Write and read aloud an improvised poem about an object chosen by others.',
    'Do an impromptu dance routine for 1 minute.',
    'Impersonate a famous character.',
    'Do the moonwalk in front of all the players.',
  ],
};
